services:
  wechat-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wechat-backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./certs:/app/certs
    env_file:
      - .env
    networks:
      - mall_mall-net
      - default

networks:
  mall_mall-net:
    external: true
