services:
  wechat-backend:
    build:
      context: .
      dockerfile: Dockerfile
    # 不加的话，默认的镜像命名规则是：
    # 项目名称_服务名称:标签
    image: wechat-backend:latest
    container_name: wechat-backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./certs:/app/certs
    env_file:
      - .env
    networks:
      - mall_mall-net
      - default

networks:
  mall_mall-net:
    external: true
